/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.libras.gui;

import br.com.libras.bo.ConsultaSHA;

import javax.swing.*;
import java.lang.invoke.ConstantCallSite;

/**
 *
 * @author wev kleyton
 * Data : 01/09/2017
 * Descrição : Classe de Login do sistema
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome :");
        jPanel1.add(jLabelNome);
        jLabelNome.setBounds(90, 270, 49, 15);

        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha :");
        jPanel1.add(jLabelSenha);
        jLabelSenha.setBounds(90, 320, 54, 15);
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(160, 250, 150, 40);
        jPanel1.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(160, 310, 150, 40);

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEntrar);
        jButtonEntrar.setBounds(100, 370, 78, 25);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair);
        jButtonSair.setBounds(230, 370, 62, 25);

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/libras/resources/bandeira-do-pará.jpg"))); // NOI18N
        jPanel1.add(jLabelImagen);
        jLabelImagen.setBounds(0, 0, 800, 445);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    public void verificaSenha(String usuario, String senha){

//        String user = "wev";
//        String senha2 = "123";
//        if (usuario.equals(user)){ //verifica se senha e igual a consulta do banco de dados
//            if (senha.equals(ConsultaSHA.geraHasSenha(senha2))){
//                JOptionPane.showConfirmDialog(null, "Desenha EWntrar no Sistema? ", "Teste", JOptionPane.YES_NO_OPTION);
//                FPrincipalLibras fPrincipalLibras = new FPrincipalLibras();
//                fPrincipalLibras.setVisible(true);
//                this.dispose();
//            }else{
//                JOptionPane.showMessageDialog(null, "Senha Incorreta!", "Erro" , JOptionPane.ERROR_MESSAGE);
//            }
//        }else{
//            JOptionPane.showMessageDialog(null, "Usuario Incorreto!", "Erro" , JOptionPane.ERROR_MESSAGE);
//
//        }

    }
    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
//        // TODO add your handling code here:
//        if (!jTextFieldNome.getText().isEmpty()){
//            if (!jPasswordFieldSenha.getText().isEmpty()){
//                String senha = ConsultaSHA.geraHasSenha(jPasswordFieldSenha.getText());
//                verificaSenha(jTextFieldNome.getText(), senha );
//            }else{
//                JOptionPane.showMessageDialog(null, "Você Tem Que Informar Uma Senha!", "Atenção", JOptionPane.WARNING_MESSAGE);
//                jPasswordFieldSenha.requestFocus();
//            }
//        }else{
//            JOptionPane.showMessageDialog(null, "Você Tem Que Informar Um Usuario!", "Atenção" , JOptionPane.WARNING_MESSAGE);
//            jTextFieldNome.requestFocus();
//        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
